#!/bin/bash

# Memory Profiling Script for Harmony Music
# Run this script to perform comprehensive memory leak analysis

echo "🎵 Harmony Music - Memory Profiling Script"
echo "==========================================="

# Check if Flutter is available
if ! command -v flutter &> /dev/null; then
    echo "❌ Flutter is not installed or not in PATH"
    exit 1
fi

# Check if app is already running
RUNNING_PROCESSES=$(ps aux | grep -E 'flutter_tool.*run' | grep -v grep)
if [ -n "$RUNNING_PROCESSES" ]; then
    echo "⚠️  Flutter app is already running. Please stop it first with 'flutter stop' or Ctrl+C"
    echo "Running processes:"
    echo "$RUNNING_PROCESSES"
    exit 1
fi

echo "📱 Starting Flutter app in debug mode for memory profiling..."

# Get device list
DEVICES=$(flutter devices --machine | jq -r '.[].id' 2>/dev/null)
if [ $? -ne 0 ] || [ -z "$DEVICES" ]; then
    echo "❌ No devices found or jq not installed. Listing devices manually:"
    flutter devices
    echo ""
    echo "Please select a device ID and run:"
    echo "  flutter run --debug -d <device_id> --observatory-port=8080"
    exit 1
fi

echo "📋 Available devices:"
flutter devices

# Use first available device (or specify one)
DEVICE_ID=$(echo "$DEVICES" | head -n1)
if [ -n "$1" ]; then
    DEVICE_ID="$1"
    echo "🎯 Using specified device: $DEVICE_ID"
else
    echo "🎯 Using default device: $DEVICE_ID"
    echo "   (Use '$0 <device_id>' to specify a different device)"
fi

echo ""
echo "🚀 Starting memory profiling session..."
echo "   Observatory will be available at: http://localhost:8080/"
echo "   DevTools will automatically open in your browser"
echo ""
echo "📋 Memory Testing Protocol:"
echo "   1. Wait for app to load completely"
echo "   2. Navigate to Home screen"
echo "   3. Take baseline heap snapshot"
echo "   4. Navigate to Player screen 10 times"
echo "   5. Return to Home and take snapshot"
echo "   6. Scroll through content and refresh 5 times"
echo "   7. Take final snapshot"
echo ""
echo "🎯 Look for retained objects >1MB in heap snapshots"
echo "📊 Normal memory range: 25-45MB, Warning: >70MB"
echo ""

# Start the app with debugging enabled
flutter run --debug \
    -d "$DEVICE_ID" \
    --observatory-port=8080 \
    --devtools-port=8081 \
    --verbose &

APP_PID=$!

# Wait for app to start
echo "⏱️  Waiting for app to start..."
sleep 10

# Check if app started successfully
if ! kill -0 $APP_PID 2>/dev/null; then
    echo "❌ App failed to start. Check the error messages above."
    exit 1
fi

echo "✅ App started successfully!"
echo ""
echo "🔍 DevTools should open automatically. If not, visit:"
echo "   http://localhost:8081"
echo ""
echo "🧠 Memory Analysis Steps:"
echo "   1. Go to 'Memory' tab in DevTools"
echo "   2. Click 'Take Snapshot' for baseline"
echo "   3. Follow the testing protocol above"
echo "   4. Compare snapshots for memory growth"
echo ""
echo "📱 App Controls:"
echo "   • Press 'r' to hot reload"
echo "   • Press 'R' to hot restart"
echo "   • Press 'q' to quit"
echo ""

# Function to create heap snapshots directory
create_snapshots_dir() {
    SNAPSHOTS_DIR="./memory_snapshots"
    mkdir -p "$SNAPSHOTS_DIR"
    echo "📁 Heap snapshots will be saved to: $SNAPSHOTS_DIR"
}

create_snapshots_dir

echo "🎯 MEMORY TESTING CHECKLIST:"
echo "   □ Baseline heap snapshot taken"
echo "   □ Navigate Player ↔ Home 10 times"
echo "   □ Player navigation heap snapshot taken"
echo "   □ Scroll and refresh Home screen 5 times"
echo "   □ Home interaction heap snapshot taken"
echo "   □ Compare snapshots for memory leaks"
echo "   □ Check for retained controllers >1MB"
echo ""

# Wait for user to complete testing
echo "⌚ Press Enter when you've completed memory testing..."
read -p ""

echo "📊 Generating memory analysis summary..."

# Create a simple memory report template
cat > memory_analysis_results.md << EOF
# Memory Analysis Results

**Date**: $(date)
**Device**: $DEVICE_ID
**Flutter Version**: $(flutter --version | head -n1)

## Test Results

### Baseline Measurement
- [ ] Memory usage: ___MB
- [ ] Heap snapshot taken: ___

### Player Navigation Test (10 cycles)
- [ ] Memory after test: ___MB
- [ ] Memory growth: ___MB
- [ ] Retained objects >1MB: ___

### Home Interaction Test (5 refreshes)
- [ ] Memory after test: ___MB
- [ ] Total memory growth: ___MB
- [ ] ScrollController leaks detected: ___

### Overall Assessment
- [ ] Memory leak risk: LOW/MEDIUM/HIGH
- [ ] Action required: YES/NO
- [ ] Notes: 

## Recommendations
- [ ] Monitor retained objects in heap snapshots
- [ ] Check ScrollControllerManager effectiveness
- [ ] Verify proper disposal of AnimationControllers
- [ ] Review PanelController lifecycle management

---
Generated by memory_profile_script.sh
EOF

echo "✅ Memory analysis template created: memory_analysis_results.md"
echo "📝 Please fill in the results based on your DevTools observations"

# Stop the app
echo "🛑 Stopping Flutter app..."
kill $APP_PID 2>/dev/null
wait $APP_PID 2>/dev/null

echo "🎉 Memory profiling session completed!"
echo "📋 Next steps:"
echo "   1. Review heap snapshots in DevTools"
echo "   2. Fill in memory_analysis_results.md"
echo "   3. Check dispose_issues.md for controller analysis"
echo "   4. Address any memory leaks found"
